### ISSUE TITLE
'openssl/opensslconf.h' file not found

### ISSUE THREAD

**Issue by pinkowitz** [Lejdborg/NMSSH#142]
Added through cocoapods - getting this error.

It will work if I manually rewrite the import statements to leave out the openssl/ part and enclose in quotes ("opensslconf.h"), but given that there are hundreds of import statements that would need to be manually updated with every pod update, it's not viable.

Tried using compiled library instead, but that generates symbol conflicts with the OpenTok library we  use.

Open to any suggestions on how to get this working. TIA for your input

**Comment by Frugghi** [comment]
That's strange, I don't see any error with Cocoapods. Maybe there is a conflict between OpenTok and NMSSH?

**Comment by wangdingkang** [comment]
I'm new to Xcode, and get the same error using cocoapods. I don't import any library that would conflict with NMSSH. I think there should be a folder called openssl in folder NMSSH, but not found in Xcode. 
![screen shot 2015-07-16 at 2 08 59 pm](https://cloud.githubusercontent.com/assets/10730725/8731279/4280d50e-2bc4-11e5-82c5-bdaa42e078ce.png)

Any solution?

**Comment by Frugghi** [comment]
Your Podfile has the `use_frameworks!` flag?

**Comment by wangdingkang** [comment]
Yeah, here is the podfile:
![screen shot 2015-07-16 at 2 19 38 pm](https://cloud.githubusercontent.com/assets/10730725/8731500/c2c306aa-2bc5-11e5-9be4-8e71f59ebbc4.png)

**Comment by Frugghi** [comment]
I think to know how to fix the podspec but I can't do it right now, you have to wait the end of the week :(
Otherwise removing `use_franeworks!` should fix the issue.

**Comment by wangdingkang** [comment]
Another library is written in Swift, it seems I cannot remove the flag...
![screen shot 2015-07-16 at 2 31 05 pm](https://cloud.githubusercontent.com/assets/10730725/8731764/745d8448-2bc7-11e5-94f4-18818f70813e.png)
Maybe I can try to update my CocoaPod.
Thank you, anyway.

**Comment by Frugghi** [comment]
If the other library is written in Swift you can remove the flag. As a temporary fix you can manually delete the OpenSSL headers from NMSSH, they are not required.
Otherwise you can import NMSSH manually until I'll fix the podspec.

**Comment by wangdingkang** [comment]
I remove the JLToast and delete the flag, it works well. Looks like the flag is the cause. But I still can't import JFToast, do you know how to import Swift pod without this flag? Otherwise I need to import JFToast in some other way.

**Comment by Frugghi** [comment]
NMSSH 2.2.2 should fix the issue.

**Comment by gurinderhans** [comment]
This seems to be happening again in 2.2.5
![screen shot 2016-04-12 at 1 48 36 am](https://cloud.githubusercontent.com/assets/3400083/14454715/b8cad942-0050-11e6-9816-42e84edd2b51.png)
